repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
    maxkb: 1024
  - id: check-ast
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    types: [python]

  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]
